version: '3.8'

services:
  omex-sniper-api:
    image: ghcr.io/omex/sniper-microservice/coin-sniper-api:latest
    platform: linux/amd64
    container_name: omex-sniper-api
    ports:
      - "6780:8000"
    environment:
      # Required environment variables
      - HELIUS_API_KEY=76b8c433-0f3c-45e6-ba43-979179a978b0
      - PUMPPORTAL_API_KEY=9wr78p318rnmju326njpmn9gchhppvhbddd52nhr6t65ay3d5x662rj2b4r4up3898wpujv395k5av1h6944wwu7ctpm2e2aa51p2uaab9p30k31d912pkv68n8kemj95wu36xvp84ykuc9x4cea184u4anhp8nup4t2ga085cpjx39e5kn4rtj75678j2dadkprh9hct8kuf8
      - SOLANA_TRACKER_API=6017fe34-9c9b-49cc-91de-a6c1359223c1
      
      # Optional environment variables
      - DEBUG=${DEBUG:-false}
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      
    volumes:
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sniper-network

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - omex-sniper-api
    restart: unless-stopped
    networks:
      - sniper-network

networks:
  sniper-network:
    driver: bridge